#!/bin/bash
count=0
for a in -1 1
do
    for b in -1 1
    do
	for c in -1 1
	do
	    for d in -1 1
	    do
		{ 
		    echo $d
		    echo $c
		    echo $b
		    echo $a
		} > out$count
		((count+=1))
	    done
	done
    done
done